---
- name: Generar certificados SSL para Traefik
  hosts: loadbalancer
  become: true
  vars:
    certs_dir: "/etc/traefik/certs"
    cert_common_name: "traefik.local"

  tasks:
    - name: Asegurar que la biblioteca cryptography esté instalada
      pip:
        name: cryptography
        state: present
        executable: pip3

    - name: Asegurar que el directorio de certificados exista
      ansible.builtin.file:
        path: "{{ certs_dir }}"
        state: directory
        mode: "0755"

    - name: Eliminar certificados previos si existen
      ansible.builtin.file:
        path: "{{ certs_dir }}/{{ item }}"
        state: absent
      loop:
        - traefik.key
        - traefik.csr
        - traefik.crt

    - name: Generar clave privada
      community.crypto.openssl_privatekey:
        path: "{{ certs_dir }}/traefik.key"
        size: 2048
        mode: "0600"

    - name: Generar solicitud de certificado (CSR)
      community.crypto.openssl_csr:
        path: "{{ certs_dir }}/traefik.csr"
        privatekey_path: "{{ certs_dir }}/traefik.key"
        common_name: "{{ cert_common_name }}"
        organization_name: "MyOrg"

    - name: Generar certificado autofirmado
      community.crypto.x509_certificate:
        path: "{{ certs_dir }}/traefik.crt"
        privatekey_path: "{{ certs_dir }}/traefik.key"
        csr_path: "{{ certs_dir }}/traefik.csr"
        provider: selfsigned

    - name: Mostrar detalles del certificado generado
      ansible.builtin.command: "openssl x509 -in {{ certs_dir }}/traefik.crt -noout -text"
      register: cert_info
      changed_when: false

    - name: Imprimir detalles del certificado
      ansible.builtin.debug:
        msg: "{{ cert_info.stdout }}"