- name: Instalar PyPy en nodos Flatcar Linux
  hosts: all
  become: true
  gather_facts: no
  tasks:
    - name: Verificar si PyPy est치 instalado
      shell: "test -f /opt/bin/python && echo 'installed' || echo 'not installed'"
      register: pypy_installed

    - name: Descargar archivo tar de PyPy
      shell: "wget -q -P /opt/ https://downloads.python.org/pypy/pypy3.9-v7.3.9-linux64.tar.bz2"
      when: pypy_installed.stdout == "not installed"

    - name: Extraer PyPy
      shell: "tar -xjf /opt/pypy3.9-v7.3.9-linux64.tar.bz2 -C /opt"
      when: pypy_installed.stdout == "not installed"

    - name: Eliminar archivo tar
      shell: "rm -rf /opt/pypy3.9-v7.3.9-linux64.tar.bz2"
      when: pypy_installed.stdout == "not installed"

    - name: Crear enlace simb칩lico para PyPy
      shell: "ln -s /opt/pypy3.9-v7.3.9-linux64/bin/pypy3 /opt/bin/python"
      when: pypy_installed.stdout == "not installed"

    - name: Verificar instalaci칩n de PyPy
      shell: "/opt/bin/python --version"
      register: pypy_version

    - name: Mostrar versi칩n de PyPy
      debug:
        msg: "PyPy version installed: {{ pypy_version.stdout }}"