---
- name: Instalación y configuración de Traefik en los Balanceadores de Carga
  hosts: loadbalancer
  become: true
  vars:
    traefik_config_dir: /etc/traefik
    docker_compose_file: /etc/traefik/docker-compose.yml
    acme_file: /etc/traefik/acme.json
    traefik_docker_image: "traefik:v3.2"
    letsencrypt_email: "tu-email@dominio.com"
    traefik_domain: "cefaslocalserver.com"
    firewall_ports:
      - 80/tcp
      - 443/tcp
      - 8080/tcp
      - 6443/tcp
    k3s_master_ip: "10.17.4.21"
    k3s_cert_path: "/var/lib/rancher/k3s/server/tls/server-ca.crt"
    traefik_k8s_cert_path: "/etc/traefik/k8s-ca.crt"
    docker_compose_version: "2.27.0"
  
  tasks:
    - name: Obtener el token de K3s desde el master
      delegate_to: "{{ k3s_master_ip }}"
      become: true
      command: >
        kubectl get secret $(kubectl get sa traefik-sa -n kube-system -o jsonpath="{.secrets[0].name}") -n kube-system -o jsonpath="{.data.token}" | base64 --decode
      register: k3s_token
      changed_when: false

    - name: Copiar el certificado del API de K3s a los balanceadores
      ansible.builtin.fetch:
        src: "{{ k3s_cert_path }}"
        dest: "/tmp/server-ca.crt"
        flat: true
      delegate_to: "{{ k3s_master_ip }}"

    - name: Enviar certificado de K3s a los balanceadores
      copy:
        src: "/tmp/server-ca.crt"
        dest: "{{ traefik_k8s_cert_path }}"
        mode: '0600'

    - name: Crear archivo `traefik.toml`
      ansible.builtin.template:
        src: templates/traefik.toml.j2
        dest: "{{ traefik_config_dir }}/traefik.toml"
        mode: '0644'

    - name: Reiniciar Traefik
      ansible.builtin.shell:
        cmd: docker-compose restart
        chdir: "{{ traefik_config_dir }}"