---
- name: Instalar y Configurar Traefik como Ingress Controller
  hosts: loadbalancer
  gather_facts: false
  become: true
  vars:
    traefik_config_dir: "/etc/traefik"
    traefik_namespace: "traefik"
    traefik_version: "v2.10"

  tasks:
    - name: Instalar Docker
      ansible.builtin.package:
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
        state: present

    - name: Iniciar y habilitar Docker
      ansible.builtin.service:
        name: docker
        state: started
        enabled: yes

    - name: Crear namespace para Traefik
      ansible.builtin.command: "kubectl create namespace {{ traefik_namespace }} --dry-run=client -o yaml | kubectl apply -f -"
      changed_when: false

    - name: Desplegar Traefik en Kubernetes
      ansible.builtin.command: "kubectl apply -f - <<EOF\napiVersion: apps/v1\nkind: Deployment\nmetadata:\n  name: traefik\n  namespace: {{ traefik_namespace }}\nspec:\n  replicas: 1\n  selector:\n    matchLabels:\n      app: traefik\n  template:\n    metadata:\n      labels:\n        app: traefik\n    spec:\n      containers:\n      - name: traefik\n        image: traefik:{{ traefik_version }}\n        args:\n        - \"--api.insecure=true\"\n        - \"--providers.kubernetesingress=true\"\n        - \"--entrypoints.web.address=:80\"\n        ports:\n        - name: web\n          containerPort: 80\n          protocol: TCP\nEOF"
      changed_when: false

    - name: Exponer Traefik con un LoadBalancer
      ansible.builtin.command: "kubectl apply -f - <<EOF\napiVersion: v1\nkind: Service\nmetadata:\n  name: traefik\n  namespace: {{ traefik_namespace }}\nspec:\n  selector:\n    app: traefik\n  ports:\n  - protocol: TCP\n    port: 80\n    targetPort: 80\n  type: LoadBalancer\nEOF"
      changed_when: false

    - name: Verificar si Traefik está en ejecución
      ansible.builtin.command: "kubectl get pods -n {{ traefik_namespace }}"
      register: traefik_status
      changed_when: false

    - name: Mostrar estado de Traefik
      ansible.builtin.debug:
        msg: "{{ traefik_status.stdout_lines }}"