---
- name: Instalar kubectl y configurar kubeconfig
  hosts: loadbalancer
  gather_facts: false
  become: true

  tasks:
    - name: Descargar kubectl
      ansible.builtin.get_url:
        url: "https://dl.k8s.io/release/v1.27.3/bin/linux/amd64/kubectl"
        dest: "/usr/local/bin/kubectl"
        mode: "0755"

    - name: Verificar la versión de kubectl
      ansible.builtin.command: "kubectl version --client"
      register: kubectl_version
      changed_when: false

    - name: Mostrar la versión de kubectl instalada
      ansible.builtin.debug:
        msg: "{{ kubectl_version.stdout }}"

    - name: Copiar kubeconfig desde master1
      ansible.builtin.copy:
        src: "/root/.kube/config"
        dest: "/root/.kube/config"
        remote_src: yes
        mode: "0600"