---
- name: Instalación y configuración de Traefik en los Balanceadores de Carga
  hosts: loadbalancer
  become: true
  vars:
    traefik_config_dir: /etc/traefik
    docker_compose_file: /etc/traefik/docker-compose.yml
    acme_file: /etc/traefik/acme.json
    traefik_docker_image: "traefik:v3.2"
    letsencrypt_email: "tu-email@dominio.com"
    traefik_domain: "cefaslocalserver.com"
    firewall_ports:
      - 80/tcp
      - 443/tcp
      - 8080/tcp
      - 6443/tcp
    k3s_master_ip: "10.17.4.21"
    docker_compose_version: "2.27.0"

  tasks:
    - name: Copiar certificados SSL a los balanceadores de carga
      ansible.builtin.copy:
        src: "files/ssl/{{ item }}"
        dest: "/etc/traefik/ssl/{{ item }}"
        mode: '0600'
      loop:
        - cefaslocalserver.com.crt
        - cefaslocalserver.com.key
      
    - name: Verificar si K3s está corriendo antes de instalar Traefik (sin Python)
      ansible.builtin.raw: "systemctl is-active k3s || echo 'not running'"
      delegate_to: "{{ k3s_master_ip }}"
      register: k3s_status
      ignore_errors: true

    - name: Fallar si K3s no está en ejecución
      fail:
        msg: "K3s no está corriendo en el nodo maestro, verifica la instalación antes de instalar Traefik."
      when: "'not running' in k3s_status.stdout"

    - name: Instalar paquetes necesarios
      ansible.builtin.yum:
        name:
          - epel-release
          - yum-utils
          - net-tools
          - vim
          - curl
          - wget
        state: present

    - name: Agregar el repositorio de Docker
      ansible.builtin.shell: |
        dnf config-manager --add-repo=https://download.docker.com/linux/centos/docker-ce.repo

    - name: Instalar Docker
      ansible.builtin.yum:
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
        state: present

    - name: Iniciar y habilitar Docker
      ansible.builtin.systemd:
        name: docker
        state: started
        enabled: true

    - name: Descargar e instalar Docker Compose
      ansible.builtin.get_url:
        url: "https://github.com/docker/compose/releases/download/v{{ docker_compose_version }}/docker-compose-linux-x86_64"
        dest: "/usr/local/bin/docker-compose"
        mode: '0755'

    - name: Crear enlace simbólico para Docker Compose
      ansible.builtin.file:
        src: "/usr/local/bin/docker-compose"
        dest: "/usr/bin/docker-compose"
        state: link

    - name: Crear directorios para Traefik
      ansible.builtin.file:
        path: "{{ item }}"
        state: directory
        mode: '0755'
      loop:
        - "{{ traefik_config_dir }}"
        - "{{ traefik_config_dir }}/ssl"

    - name: Copiar certificados SSL personalizados
      ansible.builtin.copy:
        src: "files/ssl/{{ item }}"
        dest: "/etc/traefik/ssl/{{ item }}"
        mode: '0600'
      loop:
        - cefaslocalserver.com.crt
        - cefaslocalserver.com.key

    - name: Crear archivo acme.json
      ansible.builtin.file:
        path: "{{ acme_file }}"
        state: touch
        mode: '0600'

    - name: Copiar configuración de Docker Compose
      ansible.builtin.template:
        src: templates/docker-compose.yml.j2
        dest: "{{ docker_compose_file }}"

    - name: Copiar configuración de Traefik
      ansible.builtin.template:
        src: templates/traefik.toml.j2
        dest: "{{ traefik_config_dir }}/traefik.toml"

    - name: Iniciar Traefik con Docker Compose
      ansible.builtin.shell:
        cmd: docker-compose up -d
        chdir: "{{ traefik_config_dir }}"

    - name: Configurar firewall
      ansible.builtin.firewalld:
        port: "{{ item }}"
        permanent: true
        state: enabled
      loop: "{{ firewall_ports }}"
      notify: Reload firewall

  handlers:
    - name: Reload firewall
      ansible.builtin.service:
        name: firewalld
        state: reloaded