---
- name: Instalaci贸n y configuraci贸n de Traefik en LoadBalancer1
  hosts: loadbalancer
  become: true
  vars:
    traefik_config_dir: /etc/traefik
    docker_compose_file: /etc/traefik/docker-compose.yml
    acme_file: /etc/traefik/acme.json
    traefik_toml_file: /etc/traefik/traefik.toml
    traefik_docker_image: "traefik:v3.1"
    firewall_ports:
      - 80/tcp
      - 443/tcp
      - 8080/tcp
      - 6443/tcp

  tasks:
    # 1. Preparar el entorno
    - name: Actualizar paquetes del sistema
      ansible.builtin.yum:
        name: "*"
        state: latest

    - name: Instalar dependencias necesarias
      ansible.builtin.yum:
        name:
          - epel-release
          - wget
          - vim
        state: present

    - name: Configurar el repositorio de Docker
      ansible.builtin.yum_repository:
        name: docker-ce
        description: Docker CE Repository
        baseurl: https://download.docker.com/linux/centos/7/x86_64/stable
        gpgcheck: yes
        gpgkey: https://download.docker.com/linux/centos/gpg

    - name: Instalar Docker
      ansible.builtin.yum:
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
        state: present

    - name: Iniciar y habilitar Docker
      ansible.builtin.service:
        name: docker
        state: started
        enabled: true

    - name: Descargar Docker Compose
      ansible.builtin.get_url:
        url: "https://github.com/docker/compose/releases/download/v2.20.2/docker-compose-{{ ansible_system | lower }}-{{ ansible_architecture }}"
        dest: /usr/local/bin/docker-compose
        mode: '0755'

    # 2. Configurar Traefik
    - name: Crear directorio de configuraci贸n de Traefik
      ansible.builtin.file:
        path: "{{ traefik_config_dir }}"
        state: directory
        owner: root
        group: root
        mode: '0755'

    - name: Crear archivo acme.json
      ansible.builtin.file:
        path: "{{ acme_file }}"
        state: touch
        mode: '0600'
        owner: root
        group: root

    - name: Crear archivo de configuraci贸n traefik.toml
      ansible.builtin.template:
        src: traefik.toml.j2
        dest: "{{ traefik_toml_file }}"
        owner: root
        group: root
        mode: '0644'

    - name: Crear archivo docker-compose.yml
      ansible.builtin.template:
        src: docker-compose.yml.j2
        dest: "{{ docker_compose_file }}"
        owner: root
        group: root
        mode: '0644'

    # 3. Iniciar Traefik con Docker Compose
    - name: Iniciar Traefik con Docker Compose
      ansible.builtin.command:
        cmd: docker-compose up -d
        chdir: "{{ traefik_config_dir }}"

    # 4. Configurar firewall
    - name: Abrir puertos en el firewall
      ansible.builtin.firewalld:
        port: "{{ item }}"
        permanent: true
        state: enabled
      loop: "{{ firewall_ports }}"
      notify:
        - Reload firewall

  handlers:
    - name: Reload firewall
      ansible.builtin.service:
        name: firewalld
        state: reloaded