---
- name: Instalación y configuración de Traefik en los Balanceadores de Carga
  hosts: loadbalancer
  become: true
  vars:
    traefik_config_dir: /etc/traefik
    dynamic_conf_file: "/etc/traefik/dynamic_conf.toml"
    acme_file: "/etc/traefik/acme.json"
    k3s_token_file: "/etc/traefik/k3s_token"
    k3s_cert_file: "/etc/traefik/k8s-ca.crt"
    k3s_master_ip: "10.17.4.21"

  tasks:
    - name: Obtener el token de K3s desde el master sin Python
      ansible.builtin.raw: "sudo cat /var/lib/rancher/k3s/server/node-token"
      delegate_to: "{{ k3s_master_ip }}"
      register: k3s_token
      changed_when: false

    - name: Obtener el certificado del API de K3s desde el master
      ansible.builtin.raw: "sudo cat /var/lib/rancher/k3s/server/tls/server-ca.crt"
      delegate_to: "{{ k3s_master_ip }}"
      register: k3s_ca_cert
      changed_when: false

    - name: Asegurar que el directorio de Traefik existe
      ansible.builtin.file:
        path: "{{ traefik_config_dir }}"
        state: directory
        mode: "0755"

    - name: Copiar el token de K3s a los balanceadores
      ansible.builtin.copy:
        content: "{{ k3s_token.stdout }}"
        dest: "{{ k3s_token_file }}"
        mode: "0600"
      when: k3s_token.stdout is defined and k3s_token.stdout | length > 0

    - name: Copiar el certificado de K3s a los balanceadores
      ansible.builtin.copy:
        content: "{{ k3s_ca_cert.stdout }}"
        dest: "{{ k3s_cert_file }}"
        mode: "0600"
      when: k3s_ca_cert.stdout is defined and k3s_ca_cert.stdout | length > 0

    - name: Crear `dynamic_conf.toml` si no existe
      ansible.builtin.file:
        path: "{{ dynamic_conf_file }}"
        state: touch
        mode: "0600"

    - name: Escribir configuración inicial en `dynamic_conf.toml`
      ansible.builtin.copy:
        dest: "{{ dynamic_conf_file }}"
        content: |
          # Dynamic configuration for Traefik
          [http]
            [http.routers]
          [tcp]
            [tcp.routers]
        mode: "0600"

    - name: Copiar configuración de Traefik
      ansible.builtin.template:
        src: templates/traefik.toml.j2
        dest: "{{ traefik_config_dir }}/traefik.toml"

    - name: Verificar que el archivo `k3s_token` existe antes de continuar
      ansible.builtin.stat:
        path: "{{ k3s_token_file }}"
      register: token_status

    - name: Verificar que el archivo `k8s-ca.crt` existe antes de continuar
      ansible.builtin.stat:
        path: "{{ k3s_cert_file }}"
      register: cert_status

    - name: Fallar si el token de K3s no se copió correctamente
      ansible.builtin.fail:
        msg: "El archivo {{ k3s_token_file }} no se encontró en el balanceador. Verifica la conexión con K3s."
      when: not token_status.stat.exists

    - name: Fallar si el certificado de K3s no se copió correctamente
      ansible.builtin.fail:
        msg: "El archivo {{ k3s_cert_file }} no se encontró en el balanceador. Verifica la conexión con K3s."
      when: not cert_status.stat.exists