---
- name: Instalación y configuración de Traefik en los Balanceadores de Carga
  hosts: loadbalancer
  become: true

  vars:
    traefik_config_dir: /etc/traefik
    docker_compose_file: /etc/traefik/docker-compose.yml
    acme_file: /etc/traefik/acme.json
    traefik_docker_image: "traefik:v3.2"
    letsencrypt_email: "tu-email@dominio.com"
    traefik_domain: "cefaslocalserver.com"
    firewall_ports:
      - 80/tcp
      - 443/tcp
      - 8080/tcp
      - 6443/tcp  # Kubernetes API

  tasks:
    - name: Verificar si K3s está corriendo antes de instalar Traefik
      ansible.builtin.raw: systemctl is-active --quiet k3s && echo "running" || echo "stopped"
      register: k3s_status
      changed_when: false
      delegate_to: "{{ groups['masters'][0] }}"
      run_once: true

    - name: Detener si K3s no está corriendo
      ansible.builtin.fail:
        msg: "K3s no está corriendo. No se instalará Traefik."
      when: k3s_status.stdout == "stopped"

    - name: Instalar Docker y dependencias
      ansible.builtin.yum:
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
          - docker-compose
        state: present

    - name: Iniciar y habilitar Docker
      ansible.builtin.systemd:
        name: docker
        state: started
        enabled: true

    - name: Crear directorios para Traefik
      ansible.builtin.file:
        path: "{{ item }}"
        state: directory
        mode: '0755'
      loop:
        - "{{ traefik_config_dir }}"
        - "{{ traefik_config_dir }}/ssl"

    - name: Crear archivo acme.json
      ansible.builtin.file:
        path: "{{ acme_file }}"
        state: touch
        mode: '0600'

    - name: Copiar configuración de Traefik
      ansible.builtin.template:
        src: templates/traefik.toml.j2
        dest: "{{ traefik_config_dir }}/traefik.toml"

    - name: Copiar configuración de Docker Compose
      ansible.builtin.template:
        src: templates/docker-compose.yml.j2
        dest: "{{ docker_compose_file }}"

    - name: Iniciar Traefik con Docker Compose
      ansible.builtin.shell:
        cmd: docker-compose up -d
        chdir: "{{ traefik_config_dir }}"

    - name: Configurar firewall
      ansible.builtin.firewalld:
        port: "{{ item }}"
        permanent: true
        state: enabled
      loop: "{{ firewall_ports }}"
      notify: Reload firewall

  handlers:
    - name: Reload firewall
      ansible.builtin.service:
        name: firewalld
        state: reloaded