[entryPoints]
  [entryPoints.web]
    address = ":80"
    [entryPoints.web.http.redirections.entrypoint]
      to = "websecure"
      scheme = "https"
      permanent = true

  [entryPoints.websecure]
    address = ":443"
    [entryPoints.websecure.http.tls]
      certResolver = "default"

  [entryPoints.k8sApi]
    address = ":6443"

[log]
  level = "INFO"

[api]
  dashboard = true
  insecure = false

[providers]
  [providers.docker]
    endpoint = "unix:///var/run/docker.sock"
    watch = true
    exposedByDefault = false

  [providers.file]
    filename = "/etc/traefik/dynamic_conf.toml"
    watch = true

[tls]
  [tls.stores]
    [tls.stores.default]
      [tls.stores.default.defaultCertificate]
        certFile = "/etc/traefik/certs/wildcard.cefaslocalserver.com.crt"
        keyFile = "/etc/traefik/certs/wildcard.cefaslocalserver.com.key"

  [tls.options]
    [tls.options.default]
      minVersion = "VersionTLS12"
      maxVersion = "VersionTLS13"
      cipherSuites = [
        "TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256",
        "TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384",
        "TLS_AES_128_GCM_SHA256",
        "TLS_AES_256_GCM_SHA384"
      ]

[certificatesResolvers]
  [certificatesResolvers.default]
    [certificatesResolvers.default.acme]
      email = "{{ letsencrypt_email }}"
      storage = "/etc/traefik/acme.json"
      caServer = "https://acme-v02.api.letsencrypt.org/directory"
      [certificatesResolvers.default.acme.httpChallenge]
        entryPoint = "web"

[http.middlewares]
  [http.middlewares.redirect-to-https.redirectScheme]
    scheme = "https"
    permanent = true

[http.routers]
  [http.routers.api]
    entryPoints = ["websecure"]
    service = "api@internal"
    rule = "Host(`traefik.cefaslocalserver.com`)"
    [http.routers.api.tls]
      certResolver = "default"

  [http.routers.k8sApi]
    entryPoints = ["k8sApi"]
    service = "k8sApi"
    rule = "Host(`api.local.cefaslocalserver.com`)"
    [http.routers.k8sApi.tls]
      certResolver = "default"
      [[tls.certificates]]
        certFile = "/etc/traefik/certs/wildcard.cefaslocalserver.com.crt"
        keyFile = "/etc/traefik/certs/wildcard.cefaslocalserver.com.key"

[http.services]
  [http.services.k8sApi.loadBalancer]
    [[http.services.k8sApi.loadBalancer.servers]]
      url = "https://10.17.4.21:6443"
    [[http.services.k8sApi.loadBalancer.servers]]
      url = "https://10.17.4.22:6443"
    [[http.services.k8sApi.loadBalancer.servers]]
      url = "https://10.17.4.23:6443"