---
- name: Configuración de Traefik en los Balanceadores de Carga con K3s
  hosts: master1  # Ajusta esto para que se ejecute en un solo nodo maestro
  become: true
  vars:
    k3s_namespace: "kube-system"
    traefik_serviceaccount: "traefik-sa"
    traefik_role: "traefik-role"
    traefik_rolebinding: "traefik-rolebinding"
    k3s_master_ip: "10.17.4.21"
    load_balancers:
      - "10.17.3.12"
      - "10.17.3.13"

  tasks:
    - name: Crear ServiceAccount para Traefik en K3s
      ansible.builtin.shell: |
        cat <<EOF | kubectl apply -f -
        apiVersion: v1
        kind: ServiceAccount
        metadata:
          name: {{ traefik_serviceaccount }}
          namespace: {{ k3s_namespace }}
        EOF
      register: sa_created
      changed_when: "'created' in sa_created.stdout"

    - name: Crear Role con permisos para Traefik
      ansible.builtin.shell: |
        cat <<EOF | kubectl apply -f -
        apiVersion: rbac.authorization.k8s.io/v1
        kind: Role
        metadata:
          name: {{ traefik_role }}
          namespace: {{ k3s_namespace }}
        rules:
          - apiGroups: [""]
            resources: ["services", "endpoints", "pods", "secrets"]
            verbs: ["get", "list", "watch"]
          - apiGroups: ["networking.k8s.io"]
            resources: ["ingresses"]
            verbs: ["get", "list", "watch"]
          - apiGroups: ["traefik.io"]
            resources: ["ingressroutes", "middlewares"]
            verbs: ["get", "list", "watch"]
        EOF
      register: role_created
      changed_when: "'created' in role_created.stdout"

    - name: Crear RoleBinding para Traefik
      ansible.builtin.shell: |
        cat <<EOF | kubectl apply -f -
        apiVersion: rbac.authorization.k8s.io/v1
        kind: RoleBinding
        metadata:
          name: {{ traefik_rolebinding }}
          namespace: {{ k3s_namespace }}
        subjects:
          - kind: ServiceAccount
            name: {{ traefik_serviceaccount }}
            namespace: {{ k3s_namespace }}
        roleRef:
          kind: Role
          name: {{ traefik_role }}
          apiGroup: rbac.authorization.k8s.io
        EOF
      register: rolebinding_created
      changed_when: "'created' in rolebinding_created.stdout"

    - name: Obtener el token del ServiceAccount de Traefik
      ansible.builtin.shell: |
        kubectl get secret $(kubectl get sa {{ traefik_serviceaccount }} -n {{ k3s_namespace }} -o jsonpath="{.secrets[0].name}") \
        -n {{ k3s_namespace }} -o jsonpath="{.data.token}" | base64 --decode
      register: traefik_k3s_token
      changed_when: false

    - name: Obtener el certificado de autenticación de K3s
      ansible.builtin.shell: cat /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
      register: k3s_ca_cert
      changed_when: false

    - name: Copiar token y certificado CA a los balanceadores de carga
      ansible.builtin.copy:
        content: "{{ traefik_k3s_token.stdout }}"
        dest: "/etc/traefik/k3s_token"
        mode: '0600'
      delegate_to: "{{ item }}"
      loop: "{{ load_balancers }}"

    - name: Copiar certificado CA a los balanceadores de carga
      ansible.builtin.copy:
        content: "{{ k3s_ca_cert.stdout }}"
        dest: "/etc/traefik/k3s_ca.crt"
        mode: '0600'
      delegate_to: "{{ item }}"
      loop: "{{ load_balancers }}"

    - name: Modificar configuración de Traefik en los balanceadores de carga
      ansible.builtin.template:
        src: templates/traefik.toml.j2
        dest: "/etc/traefik/traefik.toml"
      delegate_to: "{{ item }}"
      loop: "{{ load_balancers }}"

    - name: Reiniciar Traefik en los balanceadores de carga
      ansible.builtin.shell:
        cmd: docker restart traefik
      delegate_to: "{{ item }}"
      loop: "{{ load_balancers }}"
