---
- name: Instalación y configuración de Traefik en los balanceadores de carga
  hosts: loadbalancer
  become: true
  vars:
    traefik_config_dir: /etc/traefik
    letsencrypt_dir: /etc/traefik/letsencrypt
    certs_dir: /etc/traefik/certs
    docker_compose_file: /etc/traefik/docker-compose.yml
    acme_file: /etc/traefik/letsencrypt/acme.json
    traefik_toml_file: /etc/traefik/traefik.toml
    traefik_docker_image: "traefik:v3.2"
    letsencrypt_email: "tu-email@dominio.com"
    traefik_domain: "loadbalancer1.cefaslocalserver.com"
    firewall_ports:
      - 80/tcp
      - 443/tcp
      - 8080/tcp

  tasks:
    - name: Instalar dependencias necesarias
      ansible.builtin.yum:
        name:
          - epel-release
          - wget
          - vim
          - openssl
          - net-tools
        state: present

    - name: Instalar Docker
      ansible.builtin.shell: |
        dnf install -y docker-ce docker-ce-cli containerd.io

    - name: Crear directorios necesarios
      ansible.builtin.file:
        path: "{{ item }}"
        state: directory
        owner: root
        group: root
        mode: '0755'
      loop:
        - "{{ traefik_config_dir }}"
        - "{{ letsencrypt_dir }}"
        - "{{ certs_dir }}"

    - name: Crear archivo traefik.toml
      ansible.builtin.template:
        src: templates/traefik.toml.j2
        dest: "{{ traefik_toml_file }}"

    - name: Crear archivo docker-compose.yml
      ansible.builtin.template:
        src: templates/docker-compose.yml.j2
        dest: "{{ docker_compose_file }}"

    - name: Iniciar Traefik con Docker Compose
      ansible.builtin.shell:
        cmd: docker compose up -d
        chdir: "{{ traefik_config_dir }}"

    - name: Configurar Firewall
      ansible.builtin.firewalld:
        port: "{{ item }}"
        permanent: true
        state: enabled
      loop: "{{ firewall_ports }}"