---
- name: Instalar PyPy en nodos Flatcar Linux
  hosts: all
  become: true
  tasks:
    - name: Verificar si PyPy est치 instalado
      stat:
        path: /opt/bin/python
      register: pypy_installed

    - name: Descargar archivo tar de PyPy
      command: "wget -q -P /opt/ https://downloads.python.org/pypy/pypy3.9-v7.3.9-linux64.tar.bz2"
      when: not pypy_installed.stat.exists

    - name: Extraer PyPy
      command: "tar -xjf /opt/pypy3.9-v7.3.9-linux64.tar.bz2 -C /opt"
      when: not pypy_installed.stat.exists

    - name: Eliminar archivo tar
      command: "rm -rf /opt/pypy3.9-v7.3.9-linux64.tar.bz2"
      when: not pypy_installed.stat.exists

    - name: Crear enlace simb칩lico para PyPy
      command: "ln -s /opt/pypy3.9-v7.3.9-linux64/bin/pypy3 /opt/bin/python"
      when: not pypy_installed.stat.exists

    - name: Verificar instalaci칩n de PyPy
      command: "/opt/bin/python --version"
      register: pypy_version

    - name: Mostrar versi칩n de PyPy
      debug:
        msg: "PyPy version installed: {{ pypy_version.stdout }}"