---
- name: Generar certificados SSL para Traefik
  hosts: load_balancers
  become: true
  vars:
    certs_dir: "/etc/traefik/certs"
    cert_common_name: "traefik.local"

  tasks:
    - name: Asegurar que la biblioteca cryptography esté instalada
      ansible.builtin.pip:
        name: cryptography
        state: present
        executable: pip3

    - name: Crear directorio de certificados
      ansible.builtin.file:
        path: "{{ certs_dir }}"
        state: directory
        mode: "0755"

    - name: Generar clave privada
      community.crypto.openssl_privatekey:
        path: "{{ certs_dir }}/{{ cert_common_name }}.key"
        size: 2048
        mode: "0600"

    - name: Generar certificado autofirmado directamente (sin CSR)
      community.crypto.x509_certificate:
        path: "{{ certs_dir }}/{{ cert_common_name }}.crt"
        privatekey_path: "{{ certs_dir }}/{{ cert_common_name }}.key"
        provider: selfsigned
        selfsigned_not_after: "+3650d"
        selfsigned_subject:
          common_name: "{{ cert_common_name }}"
          organization_name: "MyOrg"

    - name: Mostrar detalles del certificado generado
      ansible.builtin.command: "openssl x509 -in {{ certs_dir }}/{{ cert_common_name }}.crt -noout -text"
      register: cert_info
      changed_when: false

    - name: Imprimir detalles del certificado
      ansible.builtin.debug:
        msg: "{{ cert_info.stdout }}"