---
- name: Generar certificados SSL autofirmados para Traefik desde localhost
  hosts: localhost
  become: false
  vars:
    certs_dir: "files/certs"
    cert_common_name: "traefik.local"

  tasks:
    - name: Crear directorio de certificados local
      file:
        path: "{{ certs_dir }}"
        state: directory
        mode: "0755"

    - name: Generar clave privada
      community.crypto.openssl_privatekey:
        path: "{{ certs_dir }}/{{ cert_common_name }}.key"
        size: 2048
        mode: "0600"

    - name: Generar CSR (Certificate Signing Request)
      community.crypto.openssl_csr:
        path: "{{ certs_dir }}/{{ cert_common_name }}.csr"
        privatekey_path: "{{ certs_dir }}/{{ cert_common_name }}.key"
        common_name: "{{ cert_common_name }}"
        organization_name: "MyOrg"
        country_name: "ES"
        state_or_province_name: "Madrid"
        locality_name: "Madrid"

    - name: Generar certificado autofirmado
      community.crypto.x509_certificate:
        path: "{{ certs_dir }}/{{ cert_common_name }}.crt"
        csr_path: "{{ certs_dir }}/{{ cert_common_name }}.csr"
        privatekey_path: "{{ certs_dir }}/{{ cert_common_name }}.key"
        provider: selfsigned
        selfsigned_not_after: "+3650d"
        selfsigned_digest: "sha256"
        mode: "0644"

    - name: Mostrar detalles del certificado
      command: "openssl x509 -in {{ certs_dir }}/{{ cert_common_name }}.crt -noout -text"
      register: cert_info
      changed_when: false

    - name: Imprimir información del certificado
      debug:
        msg: "{{ cert_info.stdout }}"

- name: Copiar certificados generados a los nodos load_balancers
  hosts: load_balancers
  become: true
  vars:
    certs_dir: "/etc/traefik/certs"
    cert_common_name: "traefik.local"
  tasks:
    - name: Crear directorio en el nodo destino
      file:
        path: "{{ certs_dir }}"
        state: directory
        mode: "0755"

    - name: Copiar certificados
      copy:
        src: "files/certs/{{ cert_common_name }}.{{ item }}"
        dest: "{{ certs_dir }}/{{ cert_common_name }}.{{ item }}"
        mode: "0644"
      loop:
        - crt
        - key