---
- name: Instalar kubectl y configurar kubeconfig en los nodos del balanceador de carga
  hosts: loadbalancer
  become: true
  vars:
    kubectl_version: "v1.27.3"
    kubectl_bin_path: "/usr/local/bin/kubectl"
    kubeconfig_path: "/root/.kube/config"

  tasks:
    - name: Verificar si kubectl ya está instalado
      ansible.builtin.command: "which kubectl"
      register: kubectl_check
      changed_when: false
      ignore_errors: true

    - name: Eliminar kubectl existente si está mal instalado
      ansible.builtin.file:
        path: "{{ kubectl_bin_path }}"
        state: absent
      when: kubectl_check.failed

    - name: Descargar kubectl
      ansible.builtin.get_url:
        url: "https://dl.k8s.io/release/{{ kubectl_version }}/bin/linux/amd64/kubectl"
        dest: "/tmp/kubectl"
        mode: "0755"
      when: kubectl_check.failed

    - name: Mover kubectl a /usr/local/bin
      ansible.builtin.command: "mv /tmp/kubectl {{ kubectl_bin_path }}"
      args:
        creates: "{{ kubectl_bin_path }}"
      when: kubectl_check.failed

    - name: Asignar permisos de ejecución a kubectl
      ansible.builtin.file:
        path: "{{ kubectl_bin_path }}"
        mode: "0755"
      when: kubectl_check.failed

    - name: Verificar nuevamente la instalación de kubectl
      ansible.builtin.command: "kubectl version --client"
      register: kubectl_verify
      changed_when: false
      ignore_errors: yes

    - name: Detener ejecución si kubectl no se instaló correctamente
      ansible.builtin.fail:
        msg: "kubectl no se instaló correctamente. Verifica el URL de descarga o permisos."
      when: kubectl_verify.failed

    - name: Asegurar que kubectl está en el PATH
      ansible.builtin.lineinfile:
        path: "/etc/profile.d/kubectl.sh"
        line: "export PATH=$PATH:/usr/local/bin"
        create: yes

    - name: Crear directorio de kubeconfig
      ansible.builtin.file:
        path: "/root/.kube"
        state: directory
        mode: "0755"

    - name: Copiar archivo de configuración kubeconfig
      ansible.builtin.copy:
        src: "files/kubeconfig"
        dest: "{{ kubeconfig_path }}"
        owner: root
        group: root
        mode: "0600"

    - name: Exportar variable de entorno para KUBECONFIG
      ansible.builtin.lineinfile:
        path: "/etc/profile"
        line: "export KUBECONFIG={{ kubeconfig_path }}"
        create: yes

    - name: Recargar perfil de usuario
      ansible.builtin.command: "source /etc/profile"
      changed_when: false