---
- name: Instalar PyPy en nodos Flatcar Linux
  hosts: all
  become: true
  gather_facts: no

  tasks:
    - name: Verificar si PyPy está instalado
      ansible.builtin.raw: "test -f /opt/bin/python && echo 'installed' || echo 'not installed'"
      register: pypy_installed
      changed_when: false

    - name: Descargar archivo tar de PyPy si no está instalado
      ansible.builtin.raw: "wget -q -P /opt/ https://downloads.python.org/pypy/pypy3.9-v7.3.9-linux64.tar.bz2"
      when: "'not installed' in pypy_installed.stdout"

    - name: Extraer PyPy si no está instalado
      ansible.builtin.raw: "tar -xjf /opt/pypy3.9-v7.3.9-linux64.tar.bz2 -C /opt"
      when: "'not installed' in pypy_installed.stdout"

    - name: Crear enlace simbólico para PyPy
      ansible.builtin.raw: "ln -s /opt/pypy3.9-v7.3.9-linux64/bin/pypy3 /opt/bin/python"
      when: "'not installed' in pypy_installed.stdout"

    - name: Verificar instalación de PyPy
      ansible.builtin.raw: "/opt/bin/python --version"
      register: pypy_version
      changed_when: false

    - name: Mostrar versión de PyPy instalada
      ansible.builtin.debug:
        msg: "PyPy instalado: {{ pypy_version.stdout }}"