---
- name: Instalar y Configurar Traefik como Ingress Controller en Docker
  hosts: load_balancers
  become: true

  vars:
    traefik_namespace: kube-system
    traefik_serviceaccount: traefik-ingress-controller
    k8s_api_vip: 10.17.5.10
    traefik_domain: "cefaslocalserver.com"
    letsencrypt_email: "youremail@example.com"

  tasks:

    - name: Instalar dependencias
      package:
        name:
          - curl
          - jq
        state: present

    - name: Crear directorio de configuración de Traefik
      file:
        path: /etc/traefik
        state: directory
        mode: '0755'

    - name: Crear ServiceAccount para Traefik
      delegate_to: "{{ groups['masters'][0] }}"
      shell: |
        kubectl -n {{ traefik_namespace }} create serviceaccount {{ traefik_serviceaccount }} || true
        kubectl create clusterrolebinding {{ traefik_serviceaccount }} \
          --clusterrole=cluster-admin \
          --serviceaccount={{ traefik_namespace }}:{{ traefik_serviceaccount }} || true

    - name: Obtener token del ServiceAccount
      delegate_to: "{{ groups['masters'][0] }}"
      shell: |
        TOKEN_NAME=$(kubectl -n {{ traefik_namespace }} get sa/{{ traefik_serviceaccount }} -o jsonpath='{.secrets[0].name}')
        kubectl -n {{ traefik_namespace }} get secret "$TOKEN_NAME" -o jsonpath='{.data.token}' | base64 -d
      register: traefik_sa_token

    - name: Crear archivo traefik.toml
      template:
        src: templates/traefik/traefik.toml.j2
        dest: /etc/traefik/traefik.toml
        mode: '0644'
      vars:
        traefik_token: "{{ traefik_sa_token.stdout }}"
        k8s_api_vip: "{{ k8s_api_vip }}"

    - name: Crear archivo docker-compose.yml
      template:
        src: templates/traefik/docker-compose.yml.j2
        dest: /etc/traefik/docker-compose.yml
        mode: '0644'

    - name: Reiniciar Traefik con Docker Compose
      shell: |
        cd /etc/traefik
        docker compose down || true
        docker compose up -d
      args:
        executable: /bin/bash