---
- name: Instalar y Configurar Traefik como Ingress Controller en Docker
  hosts: load_balancers
  become: true

  vars:
    traefik_config_dir: "/etc/traefik"
    k8s_api_vip: "10.17.5.10"
    kubeconfig_local_path: "/tmp/kubeconfig-traefik"
    kubeconfig_remote_path: "/etc/traefik/kubeconfig"

  tasks:
    - name: Eliminar conflictos con Podman
      package:
        name: podman-docker
        state: absent

    - name: Añadir repo oficial Docker CE (solo RedHat/Alma/CentOS)
      get_url:
        url: https://download.docker.com/linux/centos/docker-ce.repo
        dest: /etc/yum.repos.d/docker-ce.repo
      when: ansible_os_family == "RedHat"

    - name: Instalar Docker CE y plugins
      package:
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
          - docker-compose-plugin
        state: present

    - name: Habilitar e iniciar Docker
      systemd:
        name: docker
        enabled: yes
        state: started

    - name: Crear directorio de configuración de Traefik
      file:
        path: "{{ traefik_config_dir }}"
        state: directory
        mode: "0755"

    - name: Copiar kubeconfig desde master1 a localhost (sin usar Python en nodos Flatcar)
      delegate_to: localhost
      run_once: true
      become: false
      shell: |
        scp -o StrictHostKeyChecking=no -i /root/.ssh/cluster_openshift/key_cluster_openshift/id_rsa_key_cluster_openshift \
        core@10.17.4.21:/etc/rancher/k3s/k3s.yaml {{ kubeconfig_local_path }}

    - name: Reemplazar IP local por el VIP en kubeconfig
      delegate_to: localhost
      run_once: true
      become: false
      replace:
        path: "{{ kubeconfig_local_path }}"
        regexp: 'https://127.0.0.1:6443'
        replace: "https://{{ k8s_api_vip }}:6443"

    - name: Crear ServiceAccount y ClusterRoleBinding usando kubeconfig
      delegate_to: localhost
      run_once: true
      become: false
      shell: |
        KUBECONFIG={{ kubeconfig_local_path }} kubectl -n kube-system create serviceaccount traefik-ingress-controller --dry-run=client -o yaml | kubectl --kubeconfig={{ kubeconfig_local_path }} apply -f -
        KUBECONFIG={{ kubeconfig_local_path }} kubectl create clusterrolebinding traefik-ingress-controller --clusterrole=cluster-admin --serviceaccount=kube-system:traefik-ingress-controller --dry-run=client -o yaml | kubectl --kubeconfig={{ kubeconfig_local_path }} apply -f -

    - name: Obtener token para Traefik desde kubeconfig
      delegate_to: localhost
      run_once: true
      become: false
      shell: |
        TOKEN_NAME=$(kubectl --kubeconfig={{ kubeconfig_local_path }} -n kube-system get sa/traefik-ingress-controller -o jsonpath='{.secrets[0].name}')
        kubectl --kubeconfig={{ kubeconfig_local_path }} -n kube-system get secret $TOKEN_NAME -o jsonpath='{.data.token}' | base64 -d
      register: traefik_token_result

    - name: Copiar kubeconfig a los nodos Traefik
      copy:
        src: "{{ kubeconfig_local_path }}"
        dest: "{{ kubeconfig_remote_path }}"
        mode: "0644"

    - name: Crear archivo acme.json
      copy:
        dest: "{{ traefik_config_dir }}/acme.json"
        content: "{}"
        mode: "0600"

    - name: Crear archivo traefik.toml con token
      template:
        src: "../../templates/traefik/traefik.toml.j2"
        dest: "{{ traefik_config_dir }}/traefik.toml"
        mode: "0644"
      vars:
        traefik_token: "{{ traefik_token_result.stdout }}"

    - name: Crear archivo docker-compose.yml
      template:
        src: "../../templates/traefik/docker-compose.yml.j2"
        dest: "{{ traefik_config_dir }}/docker-compose.yml"
        mode: "0644"

    - name: Reiniciar contenedor Traefik
      shell: |
        docker compose -f {{ traefik_config_dir }}/docker-compose.yml down || true
        docker compose -f {{ traefik_config_dir }}/docker-compose.yml up -d
      args:
        executable: /bin/bash

    - name: Verificar estado de Traefik
      shell: docker ps -a | grep traefik
      register: traefik_status

    - name: Mostrar resultado
      debug:
        msg: "{{ traefik_status.stdout_lines }}"