---
- name: Instalar y Configurar Traefik como Ingress Controller en Docker
  hosts: load_balancers
  become: true
  vars:
    traefik_image: "traefik:v3.3"
    traefik_container_name: "traefik"
    traefik_config_dir: "/etc/traefik"
    traefik_domain: "{{ traefik_domain }}"
    letsencrypt_email: "{{ letsencrypt_email }}"
    docker_compose_file: "{{ traefik_config_dir }}/docker-compose.yml"
    traefik_kubeconfig_path: "{{ traefik_config_dir }}/kubeconfig"

  tasks:
    - name: Verificar si Docker está instalado
      ansible.builtin.command: "docker -v"
      register: docker_installed
      ignore_errors: yes
      changed_when: false

    - name: Instalar Docker si no está instalado
      ansible.builtin.shell: |
        dnf install -y docker docker-compose && systemctl enable --now docker
      when: docker_installed.rc != 0

    - name: Crear directorio de configuración de Traefik
      ansible.builtin.file:
        path: "{{ traefik_config_dir }}"
        state: directory
        mode: "0755"

    - name: Copiar kubeconfig desde el nodo master al controlador (localhost)
      ansible.builtin.fetch:
        src: /etc/rancher/k3s/k3s.yaml
        dest: /tmp/kubeconfig_from_master1.yaml
        flat: yes
      delegate_to: 10.17.4.21
      become: true

    - name: Modificar la IP del servidor API en kubeconfig (VIP del HAProxy)
      ansible.builtin.replace:
        path: /tmp/kubeconfig_from_master1.yaml
        regexp: 'server: https://127.0.0.1:6443'
        replace: 'server: https://10.17.5.10:6443'
      delegate_to: localhost

    - name: Copiar kubeconfig a los nodos Traefik
      ansible.builtin.copy:
        src: /tmp/kubeconfig_from_master1.yaml
        dest: "{{ traefik_kubeconfig_path }}"
        mode: "0600"

    - name: Crear archivo acme.json
      ansible.builtin.file:
        path: "{{ traefik_config_dir }}/acme.json"
        state: touch
        mode: "0600"

    - name: Crear archivo traefik.toml
      ansible.builtin.template:
        src: "../../templates/traefik/traefik.toml.j2"
        dest: "{{ traefik_config_dir }}/traefik.toml"
        mode: "0644"

    - name: Crear archivo docker-compose.yml
      ansible.builtin.template:
        src: "../../templates/traefik/docker-compose.yml.j2"
        dest: "{{ docker_compose_file }}"
        mode: "0644"

    - name: Detener cualquier contenedor Traefik anterior
      ansible.builtin.shell: docker-compose down || true
      args:
        chdir: "{{ traefik_config_dir }}"
      ignore_errors: yes

    - name: Iniciar Traefik
      ansible.builtin.shell: docker-compose up -d
      args:
        chdir: "{{ traefik_config_dir }}"

    - name: Verificar estado de Traefik
      ansible.builtin.command: docker ps -f name={{ traefik_container_name }}
      register: traefik_status
      changed_when: false

    - name: Mostrar resultado
      ansible.builtin.debug:
        msg: "{{ traefik_status.stdout_lines }}"