---
- name: Instalar kubectl y configurar kubeconfig en los nodos del balanceador de carga
  hosts: load_balancers
  become: yes
  tasks:

    - name: Verificar si kubectl ya está instalado
      command: which kubectl
      register: kubectl_installed
      ignore_errors: yes

    - name: Eliminar kubectl existente si está mal instalado
      file:
        path: /usr/local/bin/kubectl
        state: absent
      when: kubectl_installed.rc != 0

    - name: Descargar kubectl
      get_url:
        url: "https://dl.k8s.io/release/v1.29.0/bin/linux/amd64/kubectl"
        dest: "/tmp/kubectl"
        mode: '0755'
      when: kubectl_installed.rc != 0

    - name: Mover kubectl a /usr/local/bin
      command: mv /tmp/kubectl /usr/local/bin/kubectl
      when: kubectl_installed.rc != 0

    - name: Asignar permisos de ejecución a kubectl
      file:
        path: /usr/local/bin/kubectl
        mode: '0755'
      when: kubectl_installed.rc != 0

    - name: Agregar /usr/local/bin al PATH si no está
      lineinfile:
        path: /etc/profile
        line: 'export PATH=$PATH:/usr/local/bin'
        create: yes
      when: kubectl_installed.rc != 0

    - name: Cargar las variables de entorno actualizadas
      shell: source /etc/profile
      when: kubectl_installed.rc != 0

    - name: Verificar nuevamente la instalación de kubectl
      command: kubectl version --client
      register: kubectl_check
      ignore_errors: yes

    - name: Detener ejecución si kubectl no se instaló correctamente
      fail:
        msg: "kubectl no se instaló correctamente. Verifica el URL de descarga o permisos."
      when: kubectl_check.rc != 0